name: EvoTech Bot
on:
  push:
    branches:
      - main
env:
  package: protobuf
  old_version: 3.20.0
  new_version: 4.21.6
  
jobs:
  evotech_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: EvoTech Bot
        run: |
          x=`echo "import os\nos.environ['PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION'] = 'python'"; cat file`
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
      - name: Build site assets
        working-directory: ${{ github.workspace }}
        run: ls -la
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update package - by evotech bot
          title: EvoTech Bot
          body: Update Package "${{ env.package }}" By EvoTech Bot
          branch: evotech-bot-update-package-${{ env.package }}
