name: EvoTech Bot
on:
  workflow_dispatch:
    inputs:
      package:
        required: true
        default: 'protobuf'
      old_version:
        required: true
        default: '3.20.0'
      new_version:
        required: true
        default: '4.21.6'
  
jobs:
  evotech_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: EvoTech Bot
        run: |
          x=`echo "import os"; echo "os.environ['PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION'] = 'python'"; cat simple_demo.py`
          echo "$x" > simple_demo.py
          sed -i 's/${{ github.event.inputs.package }}==${{ github.event.inputs.old_version }}/${{ github.event.inputs.package }}==${{ github.event.inputs.new_version }}/g' environment.yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update package - by evotech bot
          title: EvoTech Bot
          body: Update Package "${{ github.event.inputs.package }}" By EvoTech Bot
          branch: evotech-bot-update-package-${{ github.event.inputs.package }}
